### ISSUE TITLE
Can't connect to chproxy with clickhouse-cli and DBeaver with redis cache enabled (v1.17.0)

### ISSUE THREAD

**Issue by PhantomPhreak** [ContentSquare/chproxy#222] opened 2022-09-05 09:49 UTC
Hi guys, it's me again :)

I've discovered a following problem with a v1.17.0:
After some time of the normal operation, i can't connect to chproxy instance or run any queries, using https://github.com/hatarist/clickhouse-cli or DBeaver, and getting following errors:

```
# clickhouse-cli                                                                                                                                                                    
clickhouse-cli version: 0.3.6
Connecting to <host>:443
Error: Failed to connect. (Remote end closed connection without response)
```

That's how it look like in chproxy logs
```
DEBUG: 2022/09/05 08:26:22 proxy.go:78: [ Id: 1711E74C4DFA0E1D; User "user"(1) proxying as "cluster_user"(2) to "host:8443"(2); RemoteAddr: "addr:41480"; LocalAddr
: "10.198.12.110:443"; Duration: 17 μs]: request start
```

I have a distributed redis cache for that user enabled. Re-starting chproxy instance is not helping, but re-starting the redis instance does. It seem like some data in the redis cache triggering this issue.

Here is a part of chproxy config, related to the cache and user:
```
- name: my-supa-redis-cache
  mode: redis
  redis:
    addresses:
    - redis-host:6379
    username: default
    password: <>
  expire: 300s
...
- name: user
  password: <>
  to_cluster: cluster
  to_user: cluster_user
  max_concurrent_queries: 4
  max_execution_time: 86400s
  requests_per_minute: 10
  deny_http: true
  deny_https: false
  allow_cors: true
  allowed_networks:
  - all
  cache: my-supa-redis-cache
  params: user_params
```

I set `max_execution_time: 86400s` for the reason, explained in https://github.com/ContentSquare/chproxy/issues/201#issuecomment-1210525823, because default 30s limit is way too low.

UPD: query result with a curl look like following:
```
$ echo "select 1" | curl --netrc-file netrc  -v -k  'https://host/'  --show-error  -d @-;
...
* Server auth using Basic with user 'user'       
> POST / HTTP/1.1                               
> Host: <host>                             
> Authorization: Basic ...
> User-Agent: curl/7.64.0                                  
> Accept: */*                                   
> Content-Length: 8                                     
> Content-Type: application/x-www-form-urlencoded
>                                               
* upload completely sent off: 8 out of 8 bytes  
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):      
* TLSv1.3 (IN), TLS alert, close notify (256):    
* Empty reply from server                                        
* Connection #0 to host <host> left intact  
curl: (52) Empty reply from server    
```

Do you have any ideas why this is happening?
Thanks!

**Comment by mga-chka** [comment] 2022-09-05 12:21
Weird issue. 
When I improved the redis cache feature I faced many "Empty reply from server" while I was developing the feature so it's likely due to an edge case not spotted. My feeling is that it could come from a missing TCP setting on the redis connection.

To help the troubleshooting:
- what happens if you set max_execution_time at 30 sec? 
- Is the issue happening after 300s (because the cache TTL is at 300s in your conf)?
- can you test with filesystem cache (to be sure the issue is really with redis even if you told when you restart redis the pb disappears)
- can you test with v1.16.1?

Ideally, you shoud give us a way to reproduce easily the issue locally.

FYI, some of our users are also using DBeaver or Datagrip and it works with cache activated (but we're using v1.16.1, we're planning to using the future v1.17.1)

**Comment by PhantomPhreak** [comment] 2022-09-06 11:23
This is really weird issue. I dug deeper and found following

> what happens if you set max_execution_time at 30 sec?

Query will be timed out after 30s of execution
```
Received exception from server:
[ Id: 17123DCFE3AB76E4; User ".."(1) proxying as "..."(1) to "..."(6); RemoteAddr: "..."; LocalAddr: "..."; Duration: 30092521 μs]: timeout for user "..." exceeded: 30s; query: "..."
```
30s timeout will make "*-transaction" keys to be flushed earlier and possibly will help to mitigate the issue (see below), but low timeouts are not useful with ClickHouse.

> Is the issue happening after 300s (because the cache TTL is at 300s in your conf)?

It looks so, at least the amount of time since "redis keys flushed" till "can't connect" directly correlate with the cache TTL setting. I've tried to increase it and decrease to the 30s, and i'm starting to get a connection problems in ~30s since first successfull connect. More details below

> can you test with filesystem cache (to be sure the issue is really with redis even if you told when you restart redis the pb disappears)

I haven't tried it yet, gonna try later

> can you test with v1.16.1?

Before we were running v1.16.4, and there are no such problems observed.

---
At first, both `clickhouse-cli` and DBeaver doing some queries like "SHOW DATABASES" during the connection, before showing a command promt or the list of the database. And it's cached of course. If some of those queries failed - there will be an error. I still can connect and execute any non-cached query using `curl`, when experiencing problems with `clickhouse-cli` and DBeaver, which means Chproxy instance and Redis are working fine.

At second, flushing all keys in the cache instance helps to solve the problem (without redis instance restart), thus, specific cache content causing this issue.
We have 3 different CH clusters, each has 1 redis cache configured, and we may experience problems with one cluster, when the rest are working. Thus, it's not a chproxy instance-related issue (max open files limit, connections limit, etc).

Here is the way to reproduce the issue:
a) Create a redis cache with 30s TTL, and users with `max_execution_time = 86400s`
b) Connect using `clickhouse-cli`
c) wait for 30s
d) connect again (even with the other user in the same cluster), getting the error
```
# clickhouse-cli
clickhouse-cli version: 0.3.6
Connecting to <host>
Error: Failed to connect. (Remote end closed connection without response)
```
e) There will be 2 keys in the redis:
```
redis> keys *
1) "b804d509c7159fa1923eb66f7609da0c-transaction"
2) "5e8d6e583fa2a74c71cc0a603a809feb-transaction"

redis> get b804d509c7159fa1923eb66f7609da0c-transaction
"1"
redis> get 5e8d6e583fa2a74c71cc0a603a809feb-transaction
"1"

redis> TTL b804d509c7159fa1923eb66f7609da0c-transaction
(integer) 172718
redis> TTL 5e8d6e583fa2a74c71cc0a603a809feb-transaction
(integer) 172714
```
f) delete both keys
```
redis> DEL b804d509c7159fa1923eb66f7609da0c-transaction 5e8d6e583fa2a74c71cc0a603a809feb-transaction
(integer) 2
redis> 
```
g) Connect using `clickhouse-cli`: **Successful**

So, it seem like the presense of "*-transaction" keys in redis causing this issue.
I hope this info will help to spot the bug. I'll try to reproduce the issue with a filesystem cache as well

**Comment by PhantomPhreak** [comment] 2022-09-06 11:30
Ah, and one more thing. Wheh chproxy instance is up and working, failed redis cache instance not causing any problems: fallback to the clickhouse will be performed quickly. But when redis instance is down, Chproxy refusing to start.

**Comment by mga-chka** [comment] 2022-09-06 14:16
Thanks. I think I see where it comes from although it's weird that the version 1.16.X works well (maybe because in the 1.17.X we're not using the same Redis APIs).
I'm a bit busy this week, so I don't know if I'll be able to do a fix but in the worst case scenario you'll have something the week after.

**Comment by mga-chka** [comment] 2022-09-08 07:01
Hi, 

The bug is not the what I thought.
I was able to reproduce your issue with v1.17.0 but not with the version on master. 
It's strange because the only difference btw 2 versions is an improvement about concurrent transaction handling. If you can, try to build a binary from the master branch (you just have to install golang then do a "go build" in the root folder of chproxy) and check if it solves your issue.

I don't like when I don't understand but I'll stop investigating, if you can't test version on master then wait for the future 1.17.1 (it should be released next week) and depending on whether or not your pb is sovled I'll close the issue.

**Comment by PhantomPhreak** [comment] 2022-09-08 07:08
Good news that you can actually reproduce it :)
We're using custom built chproxy image, and here is a part of the Dockerfile for the v1.17.0

```
RUN git clone https://github.com/ContentSquare/chproxy --branch v1.17.0 --single-branch
RUN make deps
RUN make release-build
```

I'll build it from the master and test it, thanks for the advice!

**Comment by mga-chka** [comment] 2022-09-12 07:55
Hi,
Any news on your tests with the version on master?

**Comment by PhantomPhreak** [comment] 2022-09-13 07:41
Hi! Good news here, it works fine with version from the master: described problem is not appearing anymore, so we can consider thus bug as fixed i suppose!

With a new version we have noticeably higher CPU usage (around 60%/core in average, befefore it was close to 0), but it's still acceptable.

Thank you for the support :)

**Comment by mga-chka** [comment] 2022-09-13 08:39
Good to here that.

`With a new version we have noticeably higher CPU usage (around 60%/core in average, befefore it was close to 0), but it's still acceptable.`
you mean between 1.17.0 and 1.17.1/master or between 1.16.X and 1.17.0?

**Comment by PhantomPhreak** [comment] 2022-09-13 08:49
> between 1.16.X and 1.17.0?

this one, we haven't tried 1.17.1 yet, but i'm gonna try it now :)

**Comment by mga-chka** [comment] 2022-09-13 09:11
ok, I'm closing the issue.
I'll add an issue regarding CPU usage but, since chproxy process queries faster in 1.17.0, this might be why the cpu usage is bigger.
nb: If you're looking at using 1.17.1 in your production, you should look at the max_payload_size new feature that avoids caching big results in redis (and therefore having many useless cache misses because redis has to flush out many small query results to store the big result).

**Closed as completed by mga-chka** 2022-09-13 09:11 UTC
Labels: bug

**Comment by PhantomPhreak** [comment] 2022-09-13 09:13
`max_payload_size` seem very useful tunable, thank you for the tip!
