### ISSUE TITLE
[attempt to complete transaction] entry not found for key

### ISSUE THREAD

**Issue by woozhijun** [ContentSquare/chproxy#280] opened 2022-12-15 07:15 UTC
Report an error by viewing the log:
`ERROR: 2022/12/15 06:10:21 transaction_registry_inmem.go:80: [attempt to complete transaction] entry not found for key: 522a4cae58031153f199bb4b0e2d5854, registering new entry with 1 status`

Look code:
<img width="778" alt="image" src="https://user-images.githubusercontent.com/5228147/207796186-04cfc6cc-49f9-44e6-9bda-ce226e7bdb9e.png">

version:
1.19.0

key configuration:
```
 parms:
    - key: "max_execution_time"
       value: "1800"

  - name: "shortterm"
    mode: "file_system"
    file_system:
      dir: "/data3/chproxy/shortterm/cachedir"
      max_size: 30Gb
    expire: 1800s
    grace_time: 120s
```

And,  Not sure where the problem is.

**Comment by sigua-cs** [comment] 2022-12-19 16:32
Hello @woozhijun . 
First of all, thank you for reporting this issue.
Could you please provide the scenario to reproduce the issue?

**Comment by sigua-cs** [comment] 2023-01-03 10:11
@woozhijun , did you notice my previous message?

**Comment by mga-chka** [comment] 2023-01-12 13:00
@woozhijun we're closing the issue since you're not giving more information and we're unable to reproduce the issue.
Feel free to repon the issue and give more information if you still face the issue

**Comment by woozhijun** [comment] 2023-03-02 03:58
@mga-chka @sigua-cs 
I’am sorry.  
The problem still exists, but it doesn't seem to affect the normal query, but it just keeps re-registering。

![image](https://user-images.githubusercontent.com/5228147/222327317-b731a4ae-b048-43a5-bd99-2589f072e1fc.png)

**Comment by woozhijun** [comment] 2023-03-02 04:13
Hi.  @sigua-cs @mga-chka 
In addition， There are many exceptions， I hope you can help me。 Thx

![image](https://user-images.githubusercontent.com/5228147/222329341-040df393-2c86-488f-8950-353420a092f5.png)

**Comment by mga-chka** [comment] 2023-03-02 12:23
what do you mean by `normal query`  and what are the kind of queries affected by this issue?

**Comment by woozhijun** [comment] 2023-03-06 06:42
> what do you mean by `normal query` and what are the kind of queries affected by this issue?

From the performance of the query results, there is no exception. I'm not sure what this exception means？

**Comment by mga-chka** [comment] 2023-03-06 18:12
you said `The problem still exists, but it doesn't seem to affect the normal query, but it just keeps re-registering`, which means the issue happens for only some queries. What is the difference btw the queries that produce the exception and the others (the one you called `normal`)?

**Comment by mga-chka** [comment] 2023-09-27 08:28
I'm closing this issue since it's stale. Feel free to reopen it if you have more information so that we can reproduce it

**Closed as completed by mga-chka** 2023-09-27 08:28 UTC
Labels: bug, need more info
